-- Criar o Database
CREATE DATABASE IF NOT EXISTS COFRINHO;

-- Selecionar o Database
USE COFRINHO;

-- Tabela com os usuários do sistema
CREATE TABLE IF NOT EXISTS PESSOAS (
	ID_PESSOA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(200) NOT NULL,
    IDADE INT
);

-- Tabela com as categorias das transações
-- FINALIDADE --> 0 = AMBAS, -1 = DESPESA, 1 = RECEITA
CREATE TABLE IF NOT EXISTS CATEGORIAS (
	ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(400),
    FINALIDADE INT NOT NULL
);

-- Tabela com as transações catalogadas
-- O próprio valor da transações diz se ela é despesa ou receita
CREATE TABLE IF NOT EXISTS TRANSACOES (
	ID_TRANSACAO INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(400),
    VALOR FLOAT NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    ID_PESSOA INT NOT NULL,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS(ID_PESSOA)
);
