@APIRestCofrinho_HostAddress = http://localhost:5139

### OBS: testes escritos errado (a rota correta é "transacoes") são propositais para testar o redirecionamento

### GET de todas transações
GET {{APIRestCofrinho_HostAddress}}/transacao/

### GET de 1 transação pelo ID
GET {{APIRestCofrinho_HostAddress}}/transacao/1

### POST de 1 transação
POST {{APIRestCofrinho_HostAddress}}/transacoes/
Content-Type: application/json
{
  "descricao": "Salário Bernardo",
  "valor": 3500,
  "id_categoria": 4,
  "id_pessoa": 3
}

### PUT para atualizar uma transação
PUT {{APIRestCofrinho_HostAddress}}/transacoes/
Content-Type: application/json
{
  "id_Transacao": 8,
  "valor": 2000,
  "descricao": "Salário Psicologa",
  "id_categoria": 4,
  "id_pessoa": 3
}

### DELETE uma transação pelo ID
DELETE {{APIRestCofrinho_HostAddress}}/transacoes/1
