@APIRestCofrinho_HostAddress = http://localhost:5139

### OBS: testes escritos errado (a rota correta é "pessoas") são propositis para testar o redirecionamento

### GET de todas pessoas
GET {{APIRestCofrinho_HostAddress}}/pessoa/

### GET de 1 pessoa pelo ID
GET {{APIRestCofrinho_HostAddress}}/pessoa/1

### POST de 1 pessoa
POST {{APIRestCofrinho_HostAddress}}/pessoa/
Content-Type: application/json
{
  "id_pessoa": 1,
  "nome": "zézinho",
  "idade": 15
}

### PUT para atualizar uma pessoa
PUT {{APIRestCofrinho_HostAddress}}/pessoa/
Content-Type: application/json
{
  "id_pessoa": 1,
  "nome": "zé",
  "idade": 18
}

### DELETE uma pessoa pelo ID
DELETE {{APIRestCofrinho_HostAddress}}/pessoa/1
